development:
  tcorps_url: http://localhost:3000
  form_prepopulation: true

test:
  tcorps_url: http://localhost:3000
  form_prepopulation: true

staging:
  tcorps_url: http://tcorps.sunlightlabs.com
  form_prepopulation: false
  
production:
  tcorps_url: http://transparencycorps.org
  form_prepopulation: false
